version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "8080:80"
    container_name: ishan-portfolio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./images:/usr/share/nginx/html/images:ro
      - ./assets:/usr/share/nginx/html/assets:ro
